-- Migracion idempotente para recompensas, rachas e inventario FitPaw.
-- Ejecutar en Supabase SQL Editor.

CREATE TABLE IF NOT EXISTS public.usuarios_racha (
  racha_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id integer NOT NULL REFERENCES public.usuarios_cuenta(usuario_id) ON DELETE CASCADE,
  fecha_inicio date DEFAULT CURRENT_DATE,
  fecha_ultima_actividad date,
  cantidad_dias integer NOT NULL DEFAULT 0 CHECK (cantidad_dias >= 0),
  activa boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.mascota_alimento (
  alimento_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mascota_id integer NOT NULL REFERENCES public.mascota_estado(mascota_id) ON DELETE CASCADE,
  nombre_comida character varying NOT NULL,
  cantidad integer NOT NULL DEFAULT 0 CHECK (cantidad >= 0),
  beneficio_puntos integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.mascota_ropa (
  ropa_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mascota_id integer NOT NULL REFERENCES public.mascota_estado(mascota_id) ON DELETE CASCADE,
  nombre_ropa character varying NOT NULL,
  esta_equipado boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.mascota_catalogo_items (
  item_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre character varying NOT NULL,
  tipo character varying,
  beneficio_puntos integer,
  url_imagen character varying
);

CREATE TABLE IF NOT EXISTS public.mascota_items_usuario (
  usuario_item_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id integer NOT NULL REFERENCES public.usuarios_cuenta(usuario_id) ON DELETE CASCADE,
  item_id integer NOT NULL REFERENCES public.mascota_catalogo_items(item_id) ON DELETE CASCADE,
  cantidad integer NOT NULL DEFAULT 0 CHECK (cantidad >= 0),
  esta_equipado boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.mascota_inventario (
  inventario_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id integer NOT NULL REFERENCES public.usuarios_cuenta(usuario_id) ON DELETE CASCADE,
  item_id integer NOT NULL REFERENCES public.mascota_catalogo_items(item_id) ON DELETE CASCADE,
  cantidad integer NOT NULL DEFAULT 0 CHECK (cantidad >= 0),
  esta_equipado boolean NOT NULL DEFAULT false
);

ALTER TABLE public.ejercicio_cardio
  ADD COLUMN IF NOT EXISTS completado boolean NOT NULL DEFAULT false;

ALTER TABLE public.ejercicio_fuerza
  ADD COLUMN IF NOT EXISTS completado boolean NOT NULL DEFAULT false;

ALTER TABLE public.usuarios_racha
  ADD COLUMN IF NOT EXISTS cantidad_dias integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fecha_inicio date DEFAULT CURRENT_DATE,
  ADD COLUMN IF NOT EXISTS fecha_ultima_actividad date,
  ADD COLUMN IF NOT EXISTS activa boolean NOT NULL DEFAULT false;

CREATE UNIQUE INDEX IF NOT EXISTS ux_mascota_alimento_mascota_nombre
  ON public.mascota_alimento (mascota_id, lower(nombre_comida));

CREATE UNIQUE INDEX IF NOT EXISTS ux_mascota_ropa_mascota_nombre
  ON public.mascota_ropa (mascota_id, lower(nombre_ropa));

CREATE UNIQUE INDEX IF NOT EXISTS ux_mascota_items_usuario_usuario_item
  ON public.mascota_items_usuario (usuario_id, item_id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_mascota_inventario_usuario_item
  ON public.mascota_inventario (usuario_id, item_id);

CREATE INDEX IF NOT EXISTS ix_usuarios_racha_usuario_latest
  ON public.usuarios_racha (usuario_id, racha_id DESC);

CREATE INDEX IF NOT EXISTS ix_ejercicio_cardio_usuario_fecha_completado
  ON public.ejercicio_cardio (usuario_id, fecha, completado);

CREATE INDEX IF NOT EXISTS ix_ejercicio_fuerza_usuario_fecha_completado
  ON public.ejercicio_fuerza (usuario_id, fecha, completado);

COMMENT ON COLUMN public.usuarios_racha.cantidad_dias IS
  'Cantidad real de dias de racha que consume el frontend.';
